In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv(r"C:\Users\Admin\Documents\GitHub\edu-python\dirtydata.csv")
data

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
data.shape

(32, 5)

In [11]:
data.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [6]:
data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [14]:
#1 types of null values- "Empty cells"
#dropna & impute
data.Calories=data.Calories.fillna(data.Calories.median)

In [15]:
data.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [17]:
data.dropna(inplace=True)

In [18]:
data.isnull().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [19]:
#worng format data=row26 date

In [20]:
import datetime

In [22]:
data["Date"]=pd.to_datetime(data["Date"])

In [29]:
data

,Duration,Date,Pulse,Maxpulse,Calories
0,60,2020-12-01,110,130,409.1
1,60,2020-12-02,117,145,479.0
2,60,2020-12-03,103,135,340.0
3,45,2020-12-04,109,175,282.4
4,45,2020-12-05,117,148,406.0
5,60,2020-12-06,102,127,300.0
6,60,2020-12-07,110,136,374.0
7,45,2020-12-08,104,134,253.3
8,30,2020-12-09,109,133,195.1
9,60,2020-12-10,98,124,269.0
10,60,2020-12-11,103,147,329.3
11,60,2020-12-12,100,120,250.7
12,60,2020-12-12,100,120,250.7
13,60,2020-12-13,106,128,345.3
14,60,2020-12-14,104,132,379.3
15,60,2020-12-15,98,123,275.0
16,60,2020-12-16,98,120,215.2
17,60,2020-12-17,100,120,300.0
18,45,2020-12-18,90,112,<bound method NDFrame._add_numeric_operations....
19,60,2020-12-19,103,123,323.0
20,45,2020-12-20,97,125,243.0
21,60,2020-12-21,108,131,364.2
23,60,2020-12-23,130,101,300.0
24,45,2020-12-24,105,132,246.0
25,60,2020-12-25,102,126,334.5
26,60,2020-12-26,100,120,250.0
27,60,2020-12-27,92,118,241.0
28,60,2020-12-28,103,132,<bound method NDFrame._add_numeric_operations....
29,60,2020-12-29,100,132,280.0
30,60,2020-12-30,102,129,380.3
31,60,2020-12-31,92,115,243.0

In [25]:
data.loc[7,"Duration"]=45

In [28]:
data

,Duration,Date,Pulse,Maxpulse,Calories
0,60,2020-12-01,110,130,409.1
1,60,2020-12-02,117,145,479.0
2,60,2020-12-03,103,135,340.0
3,45,2020-12-04,109,175,282.4
4,45,2020-12-05,117,148,406.0
5,60,2020-12-06,102,127,300.0
6,60,2020-12-07,110,136,374.0
7,45,2020-12-08,104,134,253.3
8,30,2020-12-09,109,133,195.1
9,60,2020-12-10,98,124,269.0
10,60,2020-12-11,103,147,329.3
11,60,2020-12-12,100,120,250.7
12,60,2020-12-12,100,120,250.7
13,60,2020-12-13,106,128,345.3
14,60,2020-12-14,104,132,379.3
15,60,2020-12-15,98,123,275.0
16,60,2020-12-16,98,120,215.2
17,60,2020-12-17,100,120,300.0
18,45,2020-12-18,90,112,<bound method NDFrame._add_numeric_operations....
19,60,2020-12-19,103,123,323.0
20,45,2020-12-20,97,125,243.0
21,60,2020-12-21,108,131,364.2
23,60,2020-12-23,130,101,300.0
24,45,2020-12-24,105,132,246.0
25,60,2020-12-25,102,126,334.5
26,60,2020-12-26,100,120,250.0
27,60,2020-12-27,92,118,241.0
28,60,2020-12-28,103,132,<bound method NDFrame._add_numeric_operations....
29,60,2020-12-29,100,132,280.0
30,60,2020-12-30,102,129,380.3
31,60,2020-12-31,92,115,243.0

In [31]:
#4 Duplicate
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [33]:
data.drop_duplicates(inplace=True) #to drop duplicate row
#data

In [34]:
data.shape

(30, 5)

In [36]:
data.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [41]:
data_x=data.iloc[:,0:4]

In [42]:
data_x.head(2)

   Duration       Date  Pulse  Maxpulse
0        60 2020-12-01    110       130
1        60 2020-12-02    117       145

In [43]:
data_y=data.iloc[:,-1]

In [44]:
data_y.head(2)

0    409.1
1    479.0
Name: Calories, dtype: object